import type { Metadata } from "next";

export const metadata: Metadata = { title: "About, sources and privacy" };

export default function About() {
  return (
    <main className="wrap page">
      <h1 className="display">About peanits</h1>
      <div className="lesson-body stack" style={{ gap: 22 }}>
        <section>
          <h2 className="title">Who and why</h2>
          <p>peanits is a free sight-reading and piano-learning site made by Yirschen. There are no accounts, no paywall and no adverts.</p>
        </section>
        <section>
          <h2 className="title">Exam boards</h2>
          <p>
            peanits is independent. It is not connected with, approved by or endorsed by ABRSM or Trinity College London. ABRSM and
            Trinity College London are the names of their respective owners and are used here only to say which syllabus a page describes.
          </p>
          <p>
            Grade requirements are summarised in our own words from the boards’ published syllabuses (ABRSM Piano 2027 &amp; 2028; Trinity
            piano from 2023). Syllabuses change and we can make mistakes, so always check the official syllabus and your teacher before
            you enter an exam.
          </p>
        </section>
        <section>
          <h2 className="title">Music and scores</h2>
          <p>
            Pieces named on grade pages come from the boards’ lists and are limited to composers who died before 1956, so their music is
            in the public domain in most countries. peanits does not host scores: the links go to IMSLP, a free library, whose own
            rules and local copyright law apply to what you download. Melodies in the sight-reading practice are generated by the app.
          </p>
        </section>
        <section>
          <h2 className="title">Facts and learning content</h2>
          <p>
            Composer profiles, lessons and the glossary are written for this site and checked as carefully as we can, but they are
            a starting point, not a textbook. If something is wrong, please tell us at{" "}
            <a href="https://github.com/curdorra/peanits/issues" target="_blank" rel="noopener noreferrer">github.com/curdorra/peanits/issues</a>.
          </p>
        </section>
        <section>
          <h2 className="title">Privacy</h2>
          <p>
            Microphone audio is analysed inside your browser and is never recorded or sent anywhere. Your progress and settings are
            saved only in your own browser (local storage), and you can delete them in Settings. There are no cookies for tracking and
            no analytics.
          </p>
        </section>
      </div>
    </main>
  );
}
