export type Term = { term: string; meaning: string; cat: Cat; symbol?: string };
export type Cat = "Tempo" | "Dynamics" | "Expression" | "Articulation" | "Pedal" | "Signs" | "Theory" | "Forms" | "Ornaments" | "Symbols";

const t = (cat: Cat) => (term: string, meaning: string): Term => ({ term, meaning, cat });
const tempo = t("Tempo"), dyn = t("Dynamics"), exp = t("Expression"), art = t("Articulation"), ped = t("Pedal");
const sy = (symbol: string, term: string, meaning: string): Term => ({ symbol, term, meaning, cat: "Symbols" });
const sign = t("Signs"), th = t("Theory"), form = t("Forms"), orn = t("Ornaments");

export const GLOSSARY: Term[] = [
  // Symbols
  sy("𝄞", "Treble clef", "The G clef: it curls around the line for G above middle C. Usually the right hand"),
  sy("𝄢", "Bass clef", "The F clef: its dots frame the line for F below middle C. Usually the left hand"),
  sy("𝄡", "C clef", "Marks middle C on its line (alto and tenor clefs); rare in piano music"),
  sy("𝄔", "Brace", "Joins the two staves of piano music so they are read together"),
  sy("♯", "Sharp", "Raise the note by a semitone"),
  sy("♭", "Flat", "Lower the note by a semitone"),
  sy("♮", "Natural", "Cancel a sharp or flat: play the plain note"),
  sy("𝄪", "Double sharp", "Raise the note by two semitones (a whole tone)"),
  sy("𝄫", "Double flat", "Lower the note by two semitones (a whole tone)"),
  sy("𝄴", "Common time", "A C instead of numbers: 4/4"),
  sy("𝄵", "Cut time", "A C with a line through it: 2/2, two minim beats per bar"),
  sy("𝅝", "Whole note (semibreve)", "Four crotchet beats long"),
  sy("𝅗𝅥", "Half note (minim)", "Two beats long"),
  sy("𝅘𝅥", "Quarter note (crotchet)", "One beat long"),
  sy("𝅘𝅥𝅮", "Eighth note (quaver)", "Half a beat long; a flag, or a beam when joined to others"),
  sy("𝅘𝅥𝅯", "Sixteenth note (semiquaver)", "A quarter of a beat long; two flags or beams"),
  sy("𝅘𝅥𝅭", "Dotted note", "A dot adds half the note's length again"),
  sy("𝄻", "Whole rest", "A bar of silence in most time signatures; hangs below a line"),
  sy("𝄼", "Half rest", "Two beats of silence; sits on a line"),
  sy("𝄽", "Quarter rest", "One beat of silence"),
  sy("𝄾", "Eighth rest", "Half a beat of silence"),
  sy("𝄿", "Sixteenth rest", "A quarter of a beat of silence"),
  sy("𝄀", "Bar line", "Divides the music into bars"),
  sy("𝄁", "Double bar line", "Marks the end of a section or a change of key or time"),
  sy("𝄂", "Final bar line", "A thin and a thick line: the end of the piece"),
  sy("𝄆", "Start repeat", "Go back to here when you reach the end repeat"),
  sy("𝄇", "End repeat", "Go back to the start repeat, or to the beginning, and play again"),
  sy("𝄋", "Segno", "A sign to return to after D.S. (dal segno)"),
  sy("𝄌", "Coda", "Jump here when told 'to Coda'; the closing section"),
  sy("𝄐", "Fermata", "Hold the note or rest longer than written"),
  sy("𝄒", "Breath mark", "A tiny pause to let a phrase breathe"),
  sy("𝄓", "Caesura", "A complete, brief stop; often written as two slashes"),
  sy("𝆏", "Piano (p)", "Soft"),
  sy("𝆐𝆏", "Mezzo piano (mp)", "Moderately soft"),
  sy("𝆐𝆑", "Mezzo forte (mf)", "Moderately loud"),
  sy("𝆑", "Forte (f)", "Loud"),
  sy("𝆑𝆑", "Fortissimo (ff)", "Very loud"),
  sy("𝆒", "Crescendo hairpin", "An opening wedge: gradually louder"),
  sy("𝆓", "Diminuendo hairpin", "A closing wedge: gradually softer"),
  sy("𝆮", "Pedal mark", "Press the sustaining pedal (Ped.), then lift where the star or bracket ends"),
  sy("𝆃", "Wavy line before a chord", "Arpeggiate: play the chord's notes quickly from the bottom up"),
  sy("𝆗", "Turn", "Play the note above, the note, the note below, the note again, quickly"),
  sy("𝆘", "Inverted turn", "Play the note below, the note, the note above, the note again, quickly"),
  sy("𝄶", "8va", "Play an octave higher than written"),
  sy("𝄷", "8vb", "Play an octave lower than written"),
  sy("tr", "Trill", "Rapidly alternate the written note with the note above"),
  // Tempo
  tempo("Largo", "Broadly and slowly"),
  tempo("Lento", "Slowly"),
  tempo("Adagio", "Slowly, at ease"),
  tempo("Andante", "At a walking pace"),
  tempo("Andantino", "A little faster than andante (usually)"),
  tempo("Moderato", "At a moderate speed"),
  tempo("Allegretto", "Fairly quick; not as fast as allegro"),
  tempo("Allegro", "Quick and lively"),
  tempo("Vivace", "Lively and fast"),
  tempo("Presto", "Very fast"),
  tempo("Prestissimo", "As fast as possible"),
  tempo("Accelerando (accel.)", "Gradually getting faster"),
  tempo("Ritardando (rit.)", "Gradually getting slower"),
  tempo("Rallentando (rall.)", "Gradually getting slower"),
  tempo("Ritenuto (riten.)", "Held back: slower straight away"),
  tempo("A tempo", "Back to the original speed"),
  tempo("Tempo primo", "Back to the speed at the start"),
  tempo("Rubato", "With some freedom of time, pushing on and holding back for expression"),
  tempo("Più mosso", "More movement: quicker"),
  tempo("Meno mosso", "Less movement: slower"),
  tempo("L'istesso tempo", "At the same speed (usually when the beat unit changes)"),
  tempo("Metronome mark", "A number such as ♩ = 80: that many beats per minute"),
  // Dynamics
  dyn("Pianissimo (pp)", "Very soft"),
  dyn("Piano (p)", "Soft"),
  dyn("Mezzo piano (mp)", "Moderately soft"),
  dyn("Mezzo forte (mf)", "Moderately loud"),
  dyn("Forte (f)", "Loud"),
  dyn("Fortissimo (ff)", "Very loud"),
  dyn("Crescendo (cresc.)", "Gradually getting louder"),
  dyn("Diminuendo (dim.)", "Gradually getting softer"),
  dyn("Decrescendo (decresc.)", "Gradually getting softer"),
  dyn("Sforzando (sfz, sf)", "A sudden strong accent on one note or chord"),
  dyn("Fortepiano (fp)", "Loud, then immediately soft"),
  dyn("Subito", "Suddenly, as in subito piano"),
  dyn("Morendo", "Dying away"),
  dyn("Hairpins", "Opening or closing wedge signs for crescendo and diminuendo"),
  // Expression
  exp("Cantabile", "In a singing style"),
  exp("Dolce", "Sweetly"),
  exp("Espressivo (espress.)", "Expressively"),
  exp("Grazioso", "Gracefully"),
  exp("Maestoso", "Majestically"),
  exp("Scherzando", "Playfully"),
  exp("Giocoso", "Merrily, humorously"),
  exp("Con brio", "With vigour, with spirit"),
  exp("Con moto", "With movement"),
  exp("Agitato", "Agitated, restless"),
  exp("Animato", "Animated, lively"),
  exp("Sostenuto", "Sustained"),
  exp("Leggiero", "Lightly"),
  exp("Tranquillo", "Calmly"),
  exp("Semplice", "Simply"),
  exp("Mesto", "Sad"),
  exp("Pesante", "Heavily"),
  exp("Sempre", "Always, as in sempre legato"),
  exp("Poco", "A little"),
  exp("Poco a poco", "Little by little"),
  exp("Molto", "Very, much"),
  exp("Assai", "Very, as in allegro assai"),
  exp("Non troppo", "Not too much"),
  exp("Simile", "Continue in the same way"),
  exp("Tutti / solo", "Everyone / one player alone"),
  // Articulation
  art("Legato", "Smoothly, with no gaps between notes"),
  art("Staccato", "Short and detached, shown by a dot"),
  art("Staccatissimo", "Very short, shown by a wedge"),
  art("Tenuto", "Held for its full value, often with slight weight; shown by a short line"),
  art("Accent", "Emphasise this note; shown by >"),
  art("Marcato", "Strongly marked; shown by ^"),
  art("Slur", "A curved line over different notes: play them legato"),
  art("Tie", "A curved line joining two notes of the same pitch: play once, hold for both values"),
  art("Phrase mark", "A long slur showing a musical sentence"),
  art("Portato", "Slightly separated but still connected, shown by dots under a slur"),
  // Pedal
  ped("Sustaining pedal", "The right pedal: lifts the dampers so notes keep ringing. Marked Ped. and *, or with brackets"),
  ped("Una corda", "The left (soft) pedal; on a grand piano it shifts the hammers to strike fewer strings"),
  ped("Tre corde", "Release the una corda pedal"),
  ped("Sostenuto pedal", "The middle pedal on many grands: sustains only the notes held when it is pressed"),
  ped("Con pedale", "With pedal"),
  ped("Senza pedale", "Without pedal"),
  // Signs
  sign("Fermata (pause)", "Hold the note or rest longer than its written value"),
  sign("Da capo (D.C.)", "Go back to the beginning"),
  sign("Dal segno (D.S.)", "Go back to the sign 𝄋"),
  sign("Fine", "The end (after a D.C. or D.S.)"),
  sign("Coda", "A closing section; jump to it at the coda sign 𝄌"),
  sign("Repeat signs", "Double bar lines with dots: play the passage between them again"),
  sign("First and second time bars", "Endings used on the first and second time through a repeat"),
  sign("Ottava (8va)", "Play an octave higher than written"),
  sign("8vb", "Play an octave lower than written"),
  sign("Loco", "Back to the written pitch after 8va"),
  sign("M.d. / m.s.", "Mano destra / mano sinistra: right hand / left hand"),
  sign("Double bar line", "Marks the end of a section; a thick final bar line marks the end of the piece"),
  // Theory
  th("Key signature", "Sharps or flats at the start of each line that apply all the way through"),
  th("Time signature", "Two numbers: beats in a bar, and the note value of each beat"),
  th("Accidental", "A sharp, flat or natural written before a note; lasts until the end of the bar"),
  th("Enharmonic", "Two names for the same pitch, such as F♯ and G♭"),
  th("Semitone", "The smallest step on the piano: from one key to the very next"),
  th("Tone", "Two semitones"),
  th("Interval", "The distance between two notes, counted by letter names"),
  th("Octave", "Eight letter names apart: the same note, higher or lower"),
  th("Scale", "Notes in order, stepwise, from one note to its octave"),
  th("Chromatic scale", "Every semitone in order"),
  th("Arpeggio", "The notes of a chord played one after another"),
  th("Triad", "A three-note chord: root, third and fifth"),
  th("Tonic", "The first note of the scale; the home note (chord I)"),
  th("Subdominant", "The fourth note of the scale (chord IV)"),
  th("Dominant", "The fifth note of the scale (chord V)"),
  th("Leading note", "The seventh note of the scale, a semitone below the tonic"),
  th("Relative minor", "The minor key sharing a major key's signature, three semitones lower"),
  th("Cadence", "A pair of chords ending a phrase: perfect, imperfect, plagal or interrupted"),
  th("Modulation", "Changing key during a piece"),
  th("Anacrusis", "An upbeat: notes before the first full bar"),
  th("Syncopation", "Accents falling off the beat"),
  th("Triplet", "Three notes played in the time of two"),
  th("Compound time", "Each beat divides into three, as in 6/8"),
  th("Simple time", "Each beat divides into two, as in 2/4, 3/4, 4/4"),
  // Forms
  form("Sonata", "A substantial piece in several movements, usually for one or two instruments"),
  form("Sonatina", "A short, simpler sonata"),
  form("Study (étude)", "A piece built around one technical skill"),
  form("Prelude", "An introductory piece, or a short independent piece"),
  form("Fugue", "A piece in which one theme enters in turn in each voice, woven together"),
  form("Invention", "Bach's name for short two- and three-part contrapuntal pieces"),
  form("Minuet", "A graceful dance in 3/4"),
  form("Gavotte", "A moderate dance in 4/4 or 2/2, usually starting halfway through the bar"),
  form("Gigue", "A lively dance in compound time, often ending a Baroque suite"),
  form("Sarabande", "A slow, stately dance in triple time"),
  form("Waltz", "A dance in 3/4 with a strong first beat"),
  form("Mazurka", "A Polish dance in triple time, often accenting the second or third beat"),
  form("Polonaise", "A stately Polish dance in 3/4"),
  form("Nocturne", "A dreamy 'night piece' with a singing melody, a form named by John Field"),
  form("Rondo", "A form where a main theme keeps returning between contrasting episodes"),
  form("Theme and variations", "A tune followed by changed versions of it"),
  form("Bagatelle", "A short, light piece"),
  form("Impromptu", "A piece with the feel of an improvisation"),
  form("Toccata", "A brilliant piece showing off touch and speed"),
  form("Suite", "A set of contrasting pieces, often dances"),
  // Ornaments
  orn("Trill (tr)", "Rapid alternation of a note with the one above"),
  orn("Mordent", "A quick alternation with the note above (upper) or below (lower), then back"),
  orn("Turn", "The note above, the note, the note below, the note"),
  orn("Appoggiatura", "A leaning note that takes time from the main note"),
  orn("Acciaccatura", "A crushed grace note, played as quickly as possible; shown with a slash"),
  orn("Arpeggiando", "Spread the chord from bottom to top; shown by a wavy line"),
  orn("Glissando", "A slide across the keys"),
];

export const CATS: Cat[] = ["Symbols", "Tempo", "Dynamics", "Expression", "Articulation", "Pedal", "Signs", "Theory", "Forms", "Ornaments"];

export type Event = { year: number; label: string; text: string; era: "Before" | "Baroque" | "Classical" | "Romantic" | "Modern" };

export const TIMELINE: Event[] = [
  { year: 1600, era: "Before", label: "Harpsichord and clavichord", text: "Keyboard music is played on the harpsichord, which plucks its strings, and the quiet clavichord. Neither can change volume much by touch." },
  { year: 1700, era: "Baroque", label: "The first piano", text: "Around 1700 in Florence, Bartolomeo Cristofori builds a keyboard with hammers: the 'gravicembalo col piano e forte'." },
  { year: 1722, era: "Baroque", label: "The Well-Tempered Clavier", text: "J. S. Bach completes Book 1: a prelude and fugue in every major and minor key." },
  { year: 1741, era: "Baroque", label: "Goldberg Variations", text: "Bach's Aria with 30 variations is published." },
  { year: 1750, era: "Classical", label: "Bach dies", text: "His death is often used to mark the end of the Baroque era." },
  { year: 1762, era: "Classical", label: "Mozart, aged six", text: "Mozart writes early minuets such as K. 5 and tours Europe as a child prodigy." },
  { year: 1781, era: "Classical", label: "A keyboard duel", text: "Mozart and Clementi play in a friendly contest before Emperor Joseph II in Vienna." },
  { year: 1801, era: "Classical", label: "'Moonlight' Sonata", text: "Beethoven writes his Sonata in C♯ minor, Op. 27 No. 2. The nickname came later, from a critic." },
  { year: 1821, era: "Romantic", label: "Double escapement", text: "Sébastien Érard patents the double escapement, letting a note be repeated quickly before the key fully rises." },
  { year: 1825, era: "Romantic", label: "Iron frames", text: "Alpheus Babcock patents a one-piece cast-iron frame in the United States; iron frames allow far stronger strings." },
  { year: 1832, era: "Romantic", label: "Chopin in Paris", text: "Chopin gives his first concert in Paris, where he will spend the rest of his life." },
  { year: 1840, era: "Romantic", label: "The recital", text: "Liszt is credited with the solo piano recital: a whole concert by one pianist." },
  { year: 1848, era: "Romantic", label: "Album for the Young", text: "Robert Schumann writes 43 pieces for his daughters, real music for young players." },
  { year: 1853, era: "Romantic", label: "Steinway & Sons", text: "Steinway is founded in New York; the modern concert grand takes shape over the following decades." },
  { year: 1876, era: "Romantic", label: "The Seasons", text: "Tchaikovsky's twelve pieces appear month by month in a magazine." },
  { year: 1889, era: "Modern", label: "ABRSM founded", text: "The Associated Board of the Royal Schools of Music is founded in London to run music exams." },
  { year: 1899, era: "Modern", label: "Maple Leaf Rag", text: "Scott Joplin's rag is published and becomes a huge success." },
  { year: 1905, era: "Modern", label: "Suite bergamasque", text: "Debussy's suite, including Clair de lune, is published." },
  { year: 1908, era: "Modern", label: "Children's Corner", text: "Debussy finishes his suite for his daughter Chouchou." },
  { year: 1940, era: "Modern", label: "Mikrokosmos", text: "Bartók's 153 progressive pieces, written over many years, are published in six volumes." },
  { year: 1952, era: "Modern", label: "4′33″", text: "John Cage's piece of silence is premiered by the pianist David Tudor." },
  { year: 1983, era: "Modern", label: "MIDI", text: "The MIDI standard lets electronic keyboards talk to each other and, later, to computers and web pages." },
];
