// One-off generator for the metronome drawing. Run: node scripts/gen-art.ts
// Output is committed as static markup so the artwork never changes between builds.
import { writeFileSync } from "node:fs";
import { createPen, blobPath } from "../src/lib/pencil.ts";

const pen = createPen(100);
let s = "";
s += pen.poly([[22, 168], [108, 168], [80, 22], [50, 22]], 0.7, true);
s += pen.poly([[14, 168], [116, 168], [116, 181], [14, 181]], 0.6, true);
s += pen.poly([[48, 22], [82, 22], [82, 13], [48, 13]], 0.5, true);
for (let y = 34; y < 165; y += 6) {
  const xl = 50 - (28 * (y - 22)) / 146,
    xr = 80 + (28 * (y - 22)) / 146;
  s += pen.line(xl + 4, y, xr - 4, y, "hh", 0.5);
}
s += pen.poly([[60, 36], [70, 36], [72, 150], [58, 150]], 0.5, true);
for (const y of [50, 66, 82, 98, 114, 130]) s += pen.line(61, y, 69, y, "pn2", 0.3);
s += pen.line(65, 160, 90, 18, "pn", 0.5);
s += pen.line(65.8, 160, 90.8, 18, "pn2", 0.8);
s += pen.poly([[76, 54], [89, 56], [88, 71], [75, 69]], 0.4, true);
for (const y of [58, 62, 66]) s += pen.line(77, y, 87, y + 1, "hh", 0.3);
s += `<path class="pn" d="${blobPath(10, 10, 2, pen.next(), 0.5)}" transform="translate(60,155)"/>`;

const out = `// Generated by scripts/gen-art.ts. Do not edit by hand.
export const METRONOME_PATHS = ${JSON.stringify(s)};
`;
writeFileSync(new URL("../src/components/art-metronome.ts", import.meta.url), out);
console.log("metronome art:", s.length, "chars");
